apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 636768524979.dkr.ecr.us-west-1.amazonaws.com/narayanan-cap:latest-speakease
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "development"
          - name: DEVELOPMENT_MODE
            value: "true"
          - name: DOTENV_KEY
            value: "override"
          - name: AUTH_DB_URI
            value: "mongodb://mongo-service:27017/authdb"
          - name: FEEDBACK_DB_URI
            value: "mongodb://mongo-service:27017/feedbackDB"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
